### Get all
GET {{api-url}}/notebooks/
Accept: application/json

### Get by id
GET {{api-url}}/notebooks/1
Accept: application/json

### Create
POST {{api-url}}/notebooks/
Accept: application/json
Content-Type: application/json

{
  "name": "New notebook"
}

### Update by id
PUT {{api-url}}/notebooks/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "Renamed notebook"
}

### Delete by id
DELETE {{api-url}}/notebooks/1
Accept: application/json
Content-Type: application/json

###
