### Create
POST {{api-url}}/users/
Accept: application/json
Content-Type: application/json

{
  "firstName": "Luke",
  "lastName": "Thompson",
  "email": "luke@example.com",
  "password": "qwerty"
}

### Login
POST {{api-url}}/login/
Accept: application/json
Content-Type: application/json

{
  "email": "luke@example.com",
  "password": "qwerty"
}

### Test private
GET {{api-url}}/notebooks/
Accept: application/json
Authorization: {{auth}}

### Test private without the auth header
GET {{api-url}}/notes/
Accept: application/json
# Authorization: {{auth}} - without the auth header access will be denied

### Get current user
GET {{api-url}}/users/
Accept: application/json
Authorization: {{auth}}

###
