### Create
POST {{api-url}}/users
Accept: application/json
Content-Type: application/json

{
  "firstName": "Luke",
  "lastName": "Thompson",
  "email": "luke@example.com",
  "password": "qwerty"
}

### Login
POST {{api-url}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "luke@example.com",
  "password": "qwerty"
}

### Private
GET {{api-url}}/notebooks/
Accept: application/json
Authorization: {{auth}}

### Public
GET {{api-url}}/notes/
Accept: application/json
Authorization: {{auth}}

###
