### Get all
GET {{api-url}}/notes/
Accept: application/json
Authorization: Basic {{auth-enc}}

### Get all by notebook id
GET {{api-url}}/notes/?nbId=1
Accept: application/json
Authorization: Basic {{auth-enc}}

### Get by id
GET {{api-url}}/notes/3
Accept: application/json
Authorization: Basic {{auth-enc}}

### Create
POST {{api-url}}/notes/
Accept: application/json
Content-Type: application/json
Authorization: Basic {{auth-enc}}

{
  "title": "New note",
  "text": "Some text",
  "notebookId": "1"
}

### Update by id
PUT {{api-url}}/notes/3
Accept: application/json
Content-Type: application/json
Authorization: Basic {{auth-enc}}

{
  "title": "Renamed note",
  "text": "Another text",
  "notebookId": "1"
}

### Delete by id
DELETE {{api-url}}/notes/4
Accept: application/json
Content-Type: application/json
Authorization: Basic {{auth-enc}}

###
