### Create
POST {{api-url}}/notes
Accept: application/json
Content-Type: application/json
Authorization: {{user-auth}}

{
  "title": "New note",
  "text": "Some text",
  "notebookId": "4"
}

### Update by id
PUT {{api-url}}/notes/5
Accept: application/json
Content-Type: application/json
Authorization: {{user-auth}}

{
  "title": "Renamed note",
  "text": "Another text",
  "notebookId": "4"
}

### Delete by id
DELETE {{api-url}}/notes/5
Accept: application/json
Content-Type: application/json
Authorization: {{user-auth}}

###
