### Create
POST {{api-url}}/users
Accept: application/json
Content-Type: application/json

{
  "firstName": "Luke",
  "lastName": "Thompson",
  "email": "luke@example.com",
  "password": "qwerty"
}

### Login
POST {{api-url}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "luke@example.com",
  "password": "qwerty"
}

### Get current user as ADMIN
GET {{api-url}}/users/current
Accept: application/json
Authorization: {{admin-auth}}

### Get current user as USER
GET {{api-url}}/users/current
Accept: application/json
Authorization: {{user-auth}}

### Get all users as ADMIN
GET {{api-url}}/users
Accept: application/json
Authorization: {{admin-auth}}

### Get all users as USER - should be forbidden
GET {{api-url}}/users
Accept: application/json
Authorization: {{user-auth}}

### Delete user with public ID 36c773c8-00b0-4f94-ada1-da5b74b49de4 as ADMIN
DELETE {{api-url}}/users/36c773c8-00b0-4f94-ada1-da5b74b49de4
Accept: application/json
Authorization: {{admin-auth}}

### Update user with public ID 36c773c8-00b0-4f94-ada1-da5b74b49de4 as ADMIN
PUT {{api-url}}/users/36c773c8-00b0-4f94-ada1-da5b74b49de4
Accept: application/json
Authorization: {{admin-auth}}
Content-Type: application/json

{
  "roles": 2,
  "enabled": true
}

###
