### Create
POST {{api-url}}/users/
Accept: application/json
Content-Type: application/json

{
  "firstName": "Luke",
  "lastName": "Thompson",
  "email": "luke@example.com",
  "password": "qwerty"
}

### Get current user as ADMIN
GET {{api-url}}/users/current
Accept: application/json
Authorization: {{admin-auth}}

### Get current user as USER
GET {{api-url}}/users/current
Accept: application/json
Authorization: {{user-auth}}

### Get all users as ADMIN
GET {{api-url}}/users/
Accept: application/json
Authorization: {{admin-auth}}

### Get all users as USER - should be forbidden
GET {{api-url}}/users/
Accept: application/json
Authorization: {{user-auth}}

###
