### Get all
GET {{api-url}}/notebooks
Accept: application/json
Authorization: {{user-auth}}

### Get all notes from notebook
GET {{api-url}}/notebooks/4/notes
Accept: application/json
Authorization: {{user-auth}}

### Create
POST {{api-url}}/notebooks
Accept: application/json
Content-Type: application/json
Authorization: {{user-auth}}

{
  "name": "New notebook"
}

### Update by id
PUT {{api-url}}/notebooks/4
Accept: application/json
Content-Type: application/json
Authorization: {{user-auth}}

{
  "name": "Renamed notebook"
}

### Delete by id
DELETE {{api-url}}/notebooks/4
Accept: application/json
Content-Type: application/json
Authorization: {{user-auth}}

###
