### Send feedback
POST {{api-url}}/feedback
Accept: application/json
Content-Type: application/json
Authorization: {{user-auth}}

{
  "senderName": "User",
  "senderEmail": "user@gmail.com",
  "feedbackText": "Hello world"
}

###
