### FEEDBACK CONTROLLER ###

### Send feedback
POST {{host-url}}//feedback
Accept: application/json
Content-Type: application/json

{
  "name": "Alex",
  "from": "alex@gmail.com",
  "text": "Hello world"
}

### NOTEBOOK CONTROLLER ###

### Get all
GET {{host-url}}/notebooks/
Accept: application/json

### Get by id
GET {{host-url}}/notebooks/1
Accept: application/json

### Create
POST http://{{host-url}}/notebooks/
Accept: application/json
Content-Type: application/json

{
  "name": "New notebook"
}

### Update by id
PUT {{host-url}}/notebooks/1
Accept: application/json
Content-Type: application/json

{
  "name": "Renamed notebook"
}

### Delete by id
DELETE {{host-url}}/notebooks/1
Accept: application/json

###
